@include('backend.trainer.layouts.navbar')
  <!--  Body Wrapper -->
  <div class="page-wrapper" id="main-wrapper" data-layout="vertical" data-navbarbg="skin6" data-sidebartype="full"
    data-sidebar-position="fixed" data-header-position="fixed">
    <!-- Sidebar Start -->

    <style>
         /* Base styles for weekdays and time slots */
        .weekday, .time-slot {
            padding: 10px;
            cursor: pointer;
            transition: background-color 0.3s, color 0.3s;
            border-radius: 8px;
        }

        /* Base styles for weekdays */
        .weekday {
            flex: none;
            margin-right: 10px;
        }

        /* Base styles for time slot picker container */
        .time-slot-picker {
            background: #fff;
            box-shadow: 0 0 15px rgba(0, 0, 0, 0.1);
            border-radius: 8px;
            overflow: hidden;
            padding: 20px;
        }

        /* Flex layout for time slots */
        .time-slot-row {
            display: flex;
            flex-wrap: wrap;
            gap: 10px;
            margin-top: 10px;
        }

        /* Base styles for individual time slots */
        .time-slot {
            background-color: #f8f9fa;
            border: 1px solid #dee2e6;
            text-align: center;
            flex: 1;
            flex-basis: calc(20% - 10px); /* for 5 slots per line */
            max-width: calc(20% - 10px); 
        }

        /* Flex layout for weekdays */
        .weekdays {
            display: flex;
            overflow-x: auto;
            white-space: nowrap;
        }

        /* Style for the selected time slots and weekdays */
        .weekday.selected, .time-slot.selected {
            background-color: #FA896B; /* Blue background */
            color: white; /* White text */
            border-color: ##FA896B; /* Blue border for selected time slots */
        }

        /* Style for the container of selected slots */
        .selected-slots-container {
            margin-top: 20px;
        }

        /* List styles for selected slots list */
        #selected-slots-list {
            list-style-type: none;
            padding-left: 0;
        }

        /* Assuming the "Save" button has a class of .save-button */
        .save-button {
            background-color: #007bff; /* Blue background to match selected items */
            color: white; /* White text */
            /* Add other button styles here */
        }

    </style>
    @include('backend.trainer.layouts.sidebar')
    <!--  Sidebar End -->
    <!--  Main wrapper -->
    <div class="body-wrapper">
      <!--  Header Start -->
      @include('backend.trainer.layouts.header')
      <!--  Header End -->
      <div class="container-fluid">
        <div>
            <h1>Time Slots</h1>
        </div>

        <div class="container py-5">
            <div class="row justify-content-center">
                <div class="col-12">
                    <div class="time-slot-picker">
                        <div class="weekdays d-flex justify-content-between text-center mb-3">
                            <!-- Weekdays will be generated by jQuery -->
                        </div>
                        <div class="time-slot-row" id="time-slot-row">
                            <!-- Time slots for the selected day will be generated by jQuery -->
                        </div>
                      
                            <form class="" action="{{ route('save.timeslots') }}" method="POST" enctype="multipart/form-data">
                                @csrf
                               

                                <!-- ... other form fields ... -->

                                <!-- Hidden input for selected slots -->
                                <input type="hidden" id="selectedSlotsInput" name="selected_slots" value="">

                                <!-- ... rest of your form ... -->

                                <div class="row d-flex justify-content-end mt-3">
                                    <div class="col-3 d-flex justify-content-end">
                                        <button type="submit" id="save-slots" class="btn btn-primary">Save</button>
                                    </div>
                                </div>
                            </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
   
        
        
    </div>
  </div>
  @include('backend.trainer.layouts.footer')

  <script>
    $(document).ready(function() {
        const weekdays = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'];
        let selectedSlots = {}; // Object to hold selected slots for each day

        function generateWeekdays() {
            const $weekdays = $('.weekdays').empty();
            weekdays.forEach((day, index) => {
                const $weekday = $('<div>').addClass('weekday').text(day);
                if (index === 0) { // Set Monday as the default selected day
                    $weekday.addClass('selected');
                }
                $weekdays.append($weekday);
            });
        }

        function generateTimeSlotsForDay(day) {
            const $timeSlotRow = $('#time-slot-row').empty();
            for (let hour = 0; hour < 24; hour++) {
                let time = `${hour.toString().padStart(2, '0')}:00 - ${hour.toString().padStart(2, '0')}:45`;
                let $timeSlot = $('<div>').addClass('time-slot').text(time).data('time', time);
                
                // Mark the time slot as selected if it was previously chosen
                if (selectedSlots[day] && selectedSlots[day].includes(time)) {
                    $timeSlot.addClass('selected');
                }
                
                $timeSlotRow.append($timeSlot);
            }
        }

        function updateSelectedSlotsList() {
            const $selectedSlotsList = $('#selected-slots-list').empty();
            $.each(selectedSlots, (day, times) => {
                if (times && times.length > 0) {
                    times.forEach(time => {
                        $('<li>').text(`${day}: ${time}`).appendTo($selectedSlotsList);
                    });
                }
            });
        }

        function updateHiddenInputWithSelectedSlots() {
            let allSelectedSlots = [];
            $.each(selectedSlots, function(day, times) {
                times.forEach(time => {
                    allSelectedSlots.push(`${day}: ${time}`);
                });
            });

            $('#selectedSlotsInput').val(allSelectedSlots.join(', '));
        }

        $('.weekdays').on('click', '.weekday', function() {
            let day = $(this).text();
            $('.weekday').removeClass('selected');
            $(this).addClass('selected');
            generateTimeSlotsForDay(day); // Generate time slots for the selected day
        });

        $('#time-slot-row').on('click', '.time-slot', function() {
            let day = $('.weekday.selected').text();
            let time = $(this).data('time');
            
            if (!selectedSlots[day]) {
                selectedSlots[day] = [];
            }

            if (selectedSlots[day].includes(time)) {
                selectedSlots[day] = selectedSlots[day].filter(t => t !== time);
                $(this).removeClass('selected');
            } else {
                selectedSlots[day].push(time);
                $(this).addClass('selected');
            }

            updateSelectedSlotsList();
        });

        // Changed from '#save-slots' to 'form' to bind to the form submission event
        $('form').on('submit', function(event) {
            event.preventDefault(); // Prevent the default form submission
            updateHiddenInputWithSelectedSlots();
            this.submit(); // Submit the form after updating the hidden input
        });

        generateWeekdays(); // Populate weekdays on page load
        generateTimeSlotsForDay(weekdays[0]); // Generate time slots for Monday on page load
        updateSelectedSlotsList();
    });
</script>


</body>

</html>